### ISSUE TITLE
set key

### ISSUE THREAD

**Issue by gigamaax** [tpar-rss/redis-tool#3]
first off, thank you for this amazing utility and all the work you do on it.

I'm sorry to ask a noob question, but I would really like to be able to set keys in redis. do you have that on your roadmap at all? it would be super useful so that I can fully interact with the database without having to pop in to redis server.

**Comment by kbellRSS** [comment]
@gigamaax kick rocks

**Comment by gigamaax** [comment]
I really think you should reconsider. it will help so many people

**Comment by tpar-rss** [comment]
Implemented in [4f47709](https://github.com/tpar-rss/redis-tool/commit/4f477093bb8094fd297bcaf592e0aa51e107fefc), out of sheer coincidence. I will now close this completely useless issue
